version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/src
    working_dir: "/opt/src/server"
    links:
      - redis
    environment:
      FLASK_APP: server.py
      FLASK_DEBUG: 1
    command: ["source activate deeplearning && flask run --with-threads --host=0.0.0.0"]
  worker:
    build: .
    volumes:
      - .:/opt/src
      - ./data/keras:/root/.keras
    working_dir: "/opt/src"
    links:
      - redis
    command: ["source activate deeplearning && python -u worker.py"]
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data