version: '3'

services:
  web:
    build: .
    ports:
      - "${HIVE_PORT:-5000}:${HIVE_PORT:-5000}"
    volumes:
      - .:/opt/src
    working_dir: "/opt/src/server"
    links:
      - redis
    environment:
      FLASK_APP: server.py
      FLASK_DEBUG: 1
      REDIS_HOST: redis
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: ["source activate deephive && flask run --with-threads --host=0.0.0.0 --port=${HIVE_PORT:-5000}"]
  worker:
    build: .
    volumes:
      - .:/opt/src
      - ./data/keras:/root/.keras
    working_dir: "/opt/src"
    links:
      - redis
    environment:
      REDIS_HOST: redis
    command: ["source activate deephive && python -u worker.py"]
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data